{
 "title": "Tested Dashvoard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "1-Minute Statistics – Anomalous Readings",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ICS474_Pipeline",
     "rawSql": "SELECT\r\n  date_trunc('minute', (ts AT TIME ZONE 'Asia/Riyadh')) AS \"time\",\r\n\r\n  min(temperature) AS min_temp,\r\n  max(temperature) AS max_temp,\r\n  avg(temperature) AS avg_temp,\r\n\r\n  min(humidity)    AS min_humidity,\r\n  max(humidity)    AS max_humidity,\r\n  avg(humidity)    AS avg_humidity,\r\n\r\n  min(pressure)    AS min_pressure,\r\n  max(pressure)    AS max_pressure,\r\n  avg(pressure)    AS avg_pressure\r\nFROM public.sensor_readings\r\nWHERE $__timeFilter(ts AT TIME ZONE 'Asia/Riyadh')\r\n  AND (anomaly_flag = 1 OR is_anomaly_source = 1)\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "1-Minute Statistics – Normal Readings",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ICS474_Pipeline",
     "rawSql": "SELECT\r\n  date_trunc('minute', (ts AT TIME ZONE 'Asia/Riyadh')) AS \"time\",\r\n\r\n  min(temperature) AS min_temp,\r\n  max(temperature) AS max_temp,\r\n  avg(temperature) AS avg_temp,\r\n\r\n  min(humidity)    AS min_humidity,\r\n  max(humidity)    AS max_humidity,\r\n  avg(humidity)    AS avg_humidity,\r\n\r\n  min(pressure)    AS min_pressure,\r\n  max(pressure)    AS max_pressure,\r\n  avg(pressure)    AS avg_pressure\r\nFROM public.sensor_readings\r\nWHERE $__timeFilter(ts AT TIME ZONE 'Asia/Riyadh')\r\n  AND anomaly_flag = 0 AND is_anomaly_source = 0\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Live Pressure (Normal vs Anomaly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "ICS474_Pipeline",
     "rawSql": "SELECT\r\n  (ts AT TIME ZONE 'Asia/Riyadh') AS \"time\",\r\n\r\n  CASE\r\n    WHEN anomaly_flag = 0 AND is_anomaly_source = 0 THEN pressure\r\n  END AS \"NORMAL\",\r\n\r\n  CASE\r\n    WHEN anomaly_flag = 1 OR is_anomaly_source = 1 THEN pressure\r\n  END AS \"ANOMALY\"\r\n\r\nFROM public.sensor_readings\r\nWHERE $__timeFilter(ts AT TIME ZONE 'Asia/Riyadh')\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Live Temperature (Normal vs Anomaly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "ICS474_Pipeline",
     "rawSql": "SELECT\r\n  (ts AT TIME ZONE 'Asia/Riyadh') AS \"time\",\r\n  temperature AS value,\r\n  CASE\r\n    WHEN anomaly_flag = 1 OR is_anomaly_source = 1 THEN 'ANOMALY'\r\n    ELSE 'NORMAL'\r\n  END AS metric\r\nFROM public.sensor_readings\r\nWHERE $__timeFilter(ts AT TIME ZONE 'Asia/Riyadh')\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Live Pressure (Normal vs Anomaly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "ICS474_Pipeline",
     "rawSql": "SELECT\r\n  (ts AT TIME ZONE 'Asia/Riyadh') AS \"time\",\r\n  CASE\r\n    WHEN anomaly_flag = 0 AND is_anomaly_source = 0 THEN humidity\r\n  END AS \"NORMAL\",\r\n  CASE\r\n    WHEN anomaly_flag = 1 OR is_anomaly_source = 1 THEN humidity\r\n  END AS \"ANOMALY\"\r\nFROM public.sensor_readings\r\nWHERE $__timeFilter(ts AT TIME ZONE 'Asia/Riyadh')\r\nORDER BY 1;\r\n"
    }
   ]
  }
 ]
}